Set our own game language
h1-mod/h1-mod pull request #113
Opened 2022-06-27 13:15 UTC by jokeruarwentto

Allow the players to set their own language with an ``language.txt`` file in game's root (where ``h1-mod.exe`` is).

![image](https://user-images.githubusercontent.com/7479947/175950257-be9e15fd-91da-4a3e-ae73-ca93e13010f7.png)

(edit: closes #124)

2022-06-27 16:20 UTC, fedddddd requested changes

2022-06-27 16:20 UTC, fedddddd commented on src/client/steam/interfaces/apps.hpp
> +		const char* LanguageFileName = "language.txt";
No need for this to be a member

2022-06-27 16:20 UTC, fedddddd commented on src/client/steam/interfaces/apps.hpp
> +		const char* Language = "english";
Snake case

2022-06-27 16:20 UTC, fedddddd commented on src/client/steam/interfaces/apps.hpp
> +					Language = line.c_str();
Just use `utils::io::file_exists` and `utils::io::read_file`.
Also `std::string line` is a local variable which will be deleted after the execution of `apps()` so you should make `const char* Language` a char array and copy the result of `utils::io::read_file` to it

2022-06-27 16:21 UTC, VladWinner commented
AFAIK, the game picks up another language if you delete the zone/english folder or rename it to english_
This does not affect the client's functioning.

2022-06-27 16:52 UTC, mjkzy commented
> [Workaround] AFAIK, the game just picks up another language if you delete the `zone/english` folder or rename it to `english_`
> 
> This does not affect the client's functioning.

even if that's the case, having this language choosing is pretty good imo. i'll fix this PR up later and merge

2022-06-27 18:53 UTC, fedddddd requested changes

2022-06-27 20:06 UTC, mjkzy reviewed
you actually caught us right before we merged this PR, haha. we were gonna ship this with the next release but we postponed it to the next one after.

i like the usage of adding LUI into the question and i think we can go ahead and add this but i think the bigger issue is the fact that people's game will crash before even trying to get into game to change the option. would you agree?

2022-06-27 20:06 UTC, mjkzy commented on data/ui_scripts/language_setting/__init__.lua
> +        POPUP_RESTART_REQUIRED_TEXT = "WARNING: To work properly, you need to have your language into zone directory of your game root. You have changed your game language, wish you restart?",
"... you need to have your language's zone files in the zone directory ..."

"... do you wish to restart? ..."

2022-06-27 20:06 UTC, mjkzy commented on data/ui_scripts/language_setting/__init__.lua
> +        POPUP_NO_ZONE_FOUND_TEXT = "We are unable to find the language folder you have selected, to avoid bugs, we will not change anything.",
"... you have selected. To avoid bugs, ..."

2022-06-27 20:09 UTC, mjkzy commented on data/ui_scripts/language_setting/__init__.lua
> +    local isok, errstr, errcode = os.rename("zone/" .. language .. "/", "zone/" .. language .. "/")
forgot to add this to the review - does renaming show if the folder actually exists or something?

if it does, consider using io::directoryexists

2022-06-27 20:14 UTC, mjkzy commented on data/ui_scripts/language_setting/__init__.lua
> +    local isok, errstr, errcode = os.rename("zone/" .. language .. "/", "zone/" .. language .. "/")
we add it on the client [here](https://github.com/h1-mod/h1-mod/blob/develop/src/client/component/ui_scripting.cpp#L176) :)

2022-06-27 20:16 UTC, mjkzy commented
the images shown above look good, i must have been thinking of another menu

2022-06-27 20:52 UTC, mjkzy commented
> Yes, we may need to check if english zone folder exists else it automatically take the first language they've ? But 90% peoples, I guess, got the game through your services

it's not even that. if someone doesn't have english files but they have spanish, for example, and they try to launch, it'll default to english. however, they don't have english. this is where a random error occurs with missing content.
my solution? i'd say modify the 'MISSING CONTENT' error we have in the client and do a search of the zone directory to see if any known languages exist. if they do, then create that language.txt file and tell them to restart your game with something like "We've detected another language installed. Please restart your game to fix this error."

2022-06-27 20:54 UTC, mjkzy commented
if you wanna go ahead and try to do this, we can expand on it after revision! :)

2022-06-27 21:06 UTC, mjkzy commented
oh wow, didn't know that. does the apps() handler shit still default to "english" though?

2022-06-27 22:25 UTC, VladWinner commented
`local available_languages = {"english", "french", "italian", "german", "spanish"}`
@jokeruarwentto Can you add `russian` localization to the list?

2022-06-27 23:02 UTC, VladWinner commented
> I guess I will need help to translate it aha
[__init__ (ru).txt](https://github.com/h1-mod/h1-mod/files/8996108/__init__.ru.txt)

> English font does not like it at all!
The original font does not contain Cyrillic (33 uppercase + 33 lowercase letters), so in the Russian localization game fonts are globally replaced by one Arial-like font >.<

2022-06-27 23:05 UTC, VladWinner commented
> Yep, we need to do something there... 😞

I thought it would be more logical if this menu is displayed in the current language. So there will be no conflicts with partial character coverage in the original font.

2022-06-27 23:43 UTC, mjkzy commented
what's your discords? I can add you guys to a channel to discuss the future of this PR in the h1-mod discord

2022-06-27 23:44 UTC, VladWinner commented
> Arwent#0001

ruVlad#7778

2022-06-30 01:17 UTC, mjkzy commented
are we good to merge this PR?

2022-06-30 12:30 UTC, merged