custom bot names
h1-mod/h1-mod pull request #164
Opened 2022-07-06 03:18 UTC by mjkzy

2022-07-06 08:48 UTC, DoktorSAS commented
Whats is the json for? 
Couldn't it be done like iw4, iw5? That is, use the classic bots.txt file and each line represents a name.
I think using a text file like that is more user firendly

2022-07-06 14:25 UTC, mjkzy commented
sure, but nothing wrong with using json? you're just making a array of names and i'm just using the json submodule we already use so this doesn't change much. i like json

2022-07-06 15:37 UTC, mjkzy commented
uses `h1-mod/bots.txt` now, only side effect i've just now noticed is that when `/map_rotate` is ran and you spawn in and spawn a bot, SV_GetRandomBotName is called twice and the first name is ignored but the second one works. i assume this is because the first bot just doesn't spawn, but either way, it's not a huge issue. though, doing `/fast_restart` will use the first name and only call SV_GetRandomBotName once

2022-07-06 20:29 UTC, mjkzy commented
if i do custom clan tags, back to json it is!

2022-07-07 20:48 UTC, fedddddd requested changes

2022-07-07 20:48 UTC, fedddddd commented on src/client/component/bots.cpp
> +				console::error(utils::string::va("%s was not found.\n", bots_txt));
No need to print this imo

2022-07-07 20:48 UTC, fedddddd commented on src/client/component/bots.cpp
> +				console::info(utils::string::va("Loading name '%s' for bot names...\n", name.data()));
Same here

2022-07-07 20:48 UTC, fedddddd commented on src/client/component/bots.cpp
> +			console::info(utils::string::va("Bot ID is %d\n", bot_id));
Same here

2022-07-07 20:48 UTC, fedddddd commented on src/client/component/bots.cpp
> +		static size_t bot_id = 0;
Remove the static, or move it inside get_random_bot_name

2022-07-07 20:50 UTC, mjkzy commented on src/client/component/bots.cpp
> +				console::error(utils::string::va("%s was not found.\n", bots_txt));
left from testing, fixed

2022-07-07 23:24 UTC, merged